Implement snapshot subcommand for light-node
This command will produce a snapshot containing the full chain of block headers
and operations, but only the resulting context and receipts for the target block.

diff --git a/.drone.yml b/.drone.yml
--- a/.drone.yml
+++ b/.drone.yml
@@ -807,9 +807,10 @@ image_pull_secrets:
 ---
 ##############################################################################################################
 # This pipeline replays the application of the first 20k blocks from florencenet using the in-memory context
+# It also tests the snapshot functionality
 ##############################################################################################################
 kind: pipeline
-name: corr/replay-009-florence
+name: corr/replay-and-snapshot-009-florence
 
 trigger:
   branch:
@@ -920,6 +921,61 @@ steps:
       --tezos-data-dir=/cache/tezedge-data --bootstrap-db-path=bootstrap_db
       --tezos-context-storage=tezedge
       --network=$${NETWORK}
+
+- name: take-snapshot-and-bootstrap-test
+  image: tezedge/tezedge-ci-builder:rust-1.58.1-v11.0-octez
+  user: root
+  pull: if-not-exists
+  volumes:
+    - name: cache
+      path: /cache
+  commands:
+    - rust_libs=$(echo "`rustup show home`/toolchains/`rustup show active-toolchain | tr " " "\n" | head -1`/lib")
+    - OCTEZ_IP=$(perl -e 'use Socket; my $a = gethostbyname("octez-node"); print inet_ntoa($a)')
+    - export LD_LIBRARY_PATH="drone-cache/build_files/ffi:$rust_libs"
+    - mkdir -p ./target/release && cp drone-cache/build_files/protocol-runner ./target/release
+    - >
+      drone-cache/build_files/light-node
+      --config-file "drone-cache/build_files/tezedge/tezedge_drone.config"
+      --identity-file "drone-cache/build_files/identities/identity_6.json"
+      --protocol-runner=drone-cache/build_files/protocol-runner
+      --init-sapling-spend-params-file=drone-cache/build_files/ffi/sapling-spend.params
+      --init-sapling-output-params-file=drone-cache/build_files/ffi/sapling-output.params
+      --tezos-data-dir=/cache/tezedge-data --bootstrap-db-path=bootstrap_db
+      --tezos-context-storage=irmin
+      --network=$${NETWORK}
+      snapshot --target-path=./snapshot --block BLrv1ad4744HodQZJaeHMgNxM4bNqzxAC7q1PDMbscCoBdBjGsR # level=19900
+    - >
+      drone-cache/build_files/light-node
+      --config-file=drone-cache/build_files/tezedge/tezedge_drone.config
+      --identity-file=drone-cache/build_files/identities/identity_2.json
+      --protocol-runner=drone-cache/build_files/protocol-runner
+      --init-sapling-spend-params-file=drone-cache/build_files/ffi/sapling-spend.params
+      --init-sapling-output-params-file=drone-cache/build_files/ffi/sapling-output.params
+      --peer-thresh-low=1 --peer-thresh-high=1 --network "$${NETWORK}"
+      --tezos-data-dir=./snapshot --bootstrap-db-path=bootstrap_db
+      --tezos-context-storage=irmin --disable-bootstrap-lookup --peers="$${OCTEZ_IP}:9732" &
+      echo $! > /var/run/tezedge.pid
+    # this command waits the node to be on level 20000
+    - |
+      sh -c '
+      block=0
+      attempts=0
+      while [ $block -lt 20000 ]; do
+        sleep 5
+        b=$(curl -s localhost:18732/chains/main/blocks/head | jq .header.level)
+        block=$${b:-$block}
+        echo "===> Block level $block"
+        if [ $attempts -gt 60 ]; then
+          echo "Failed to bootstrap after 5 minutes."
+          exit 1
+        fi
+        attempts=$(($attempts + 1))
+      done
+      '
+    - echo "Bootstrapped. Killing the node and waiting for 10 seconds."
+    # terminate the node gracefully and wait to allow `valgrind` dump data
+    - kill -INT $(cat /var/run/tezedge.pid) && sleep 10
 
 # TODO - TE-261: we don't have an equivalent of this right now
 # - name: record/replay-context-action-file-test
