Default to default config + More import snapshot tests (#1007)
* Default to tezedge.config as --config-file

* CI: Add pipelines for importing snapshots with tezedge context + long running CI tests for latest snapshots

CI: Add integrity check to import snapshot tests

CI: import snapshot pipeline description

CI: Add snapshot server with import-snapshot test to longrunning CI

CI: revert some changes

CI: correct cache + level

CI: remove the file in cache after use

CI: save block hash after import

CI: remove quotes

CI: try to sync from internet

CI: tweaks

CI: more tweaks

* Update changelog with import-snapshot subcommand

diff --git a/.drone.yml b/.drone.yml
--- a/.drone.yml
+++ b/.drone.yml
@@ -689,7 +689,10 @@ image_pull_secrets:
   - docker_pull_secret
 
 ---
-
+##############################################################################################################
+# This pipeline runs a nginx file web server with file sharing and tests the import-snapshot subcommand with
+# both types of context snapshots
+##############################################################################################################
 kind: pipeline
 name: corr/import-snapshot
 
@@ -753,7 +756,7 @@ steps:
     - nginx
     - sleep infinity
 
-- name: import-snapshot
+- name: import-snapshot-with-irmin-context
   image: tezedge/tezedge-ci-builder:rust-1.58.1-v12.0-octez
   user: root
   pull: if-not-exists
@@ -769,7 +772,7 @@ steps:
     - export LD_LIBRARY_PATH="drone-cache/build_files/ffi:$rust_libs"
     - ./drone-cache/build_files/light-node import-snapshot --from http://nginx-file-server/tezedge_hangzhou_20220322-113544_BMCnDzyT2UASaz7BpM5JT5K7xwzHsv2q1A5LpZm6u4PNJuMmLpC_irmin.full --tezos-data-dir /cache
 
-- name: run-tezedge-from-imported-snapshot
+- name: run-tezedge-from-imported-snapshot-with-irmin-context
   image: tezedge/tezedge-ci-builder:rust-1.58.1-v12.0-octez
   user: root
   pull: if-not-exists
@@ -789,7 +792,7 @@ steps:
       --peer-thresh-low=1 --peer-thresh-high=1 --network "$${NETWORK}"
       --tezos-data-dir=/cache --bootstrap-db-path=bootstrap_db
       --tezos-context-storage=irmin --disable-bootstrap-lookup
-      --log-level debug &
+      --log-level debug --context-integrity-check true &
       echo $! > /var/run/tezedge.pid
     # this command waits the node to be on level 710058
     - |
@@ -797,6 +800,75 @@ steps:
       block=0
       attempts=0
       while [ $block -lt 710058 ]; do
+        sleep 5
+        b=$(curl -s localhost:18732/chains/main/blocks/head | jq .header.level)
+        block=$${b:-$block}
+        echo "===> Block level $block"
+        if [ $attempts -gt 12 ]; then
+          echo "Failed to bootstrap after a minute."
+          exit 1
+        fi
+        attempts=$(($attempts + 1))
+      done
+      '
+    - echo "Bootstrapped. Killing the node and waiting for 10 seconds."
+    # terminate the node gracefully and wait to allow `valgrind` dump data
+    - kill -INT $(cat /var/run/tezedge.pid) && sleep 10
+
+- name: cleanup-cached-tezedge-data
+  image: tezedge/tezedge-ci-builder:rust-1.58.1-v12.0-octez
+  user: root
+  pull: if-not-exists
+  volumes:
+    - name: cache
+      path: /cache
+  commands:
+    - rm -rf /cache/*
+
+- name: import-snapshot-with-tezedge-context
+  image: tezedge/tezedge-ci-builder:rust-1.58.1-v12.0-octez
+  user: root
+  pull: if-not-exists
+  environment:
+    SODIUM_USE_PKG_CONFIG: 1
+    THROTTLING_QUOTA_DISABLE: true
+  volumes:
+    - name: cache
+      path: /cache
+  commands:
+    - sleep 10
+    - rust_libs=$(echo "`rustup show home`/toolchains/`rustup show active-toolchain | tr " " "\n" | head -1`/lib")
+    - export LD_LIBRARY_PATH="drone-cache/build_files/ffi:$rust_libs"
+    - ./drone-cache/build_files/light-node import-snapshot --from http://nginx-file-server/tezedge_hangzhou_20220324-115238_BL93oyUZ2fvibSgp11kJbf1Vqz3UHQb9yyrRattSM8Tmh99X8os_tezedge.full --tezos-data-dir /cache
+
+- name: run-tezedge-from-imported-snapshot-with-tezedge-context
+  image: tezedge/tezedge-ci-builder:rust-1.58.1-v12.0-octez
+  user: root
+  pull: if-not-exists
+  volumes:
+    - name: cache
+      path: /cache
+  commands:
+    - rust_libs=$(echo "`rustup show home`/toolchains/`rustup show active-toolchain | tr " " "\n" | head -1`/lib")
+    - export LD_LIBRARY_PATH="drone-cache/build_files/ffi:$rust_libs"
+    - >
+      ./drone-cache/build_files/light-node
+      --config-file=./drone-cache/build_files/tezedge/tezedge_drone.config
+      --identity-file=./drone-cache/build_files/identities/identity_2.json
+      --protocol-runner=./drone-cache/build_files/protocol-runner
+      --init-sapling-spend-params-file=./drone-cache/build_files/ffi/sapling-spend.params
+      --init-sapling-output-params-file=./drone-cache/build_files/ffi/sapling-output.params
+      --peer-thresh-low=1 --peer-thresh-high=1 --network "$${NETWORK}"
+      --tezos-data-dir=/cache --bootstrap-db-path=bootstrap_db
+      --tezos-context-storage=tezedge --disable-bootstrap-lookup
+      --log-level debug --context-integrity-check true &
+      echo $! > /var/run/tezedge.pid
+    # this command waits the node to be on level 717507
+    - |
+      sh -c '
+      block=0
+      attempts=0
+      while [ $block -lt 717507 ]; do
         sleep 5
         b=$(curl -s localhost:18732/chains/main/blocks/head | jq .header.level)
         block=$${b:-$block}
