Add/remove baker

diff --git a/tezos/mitten/tezos-baker-012-Psithaca b/tezos/mitten/tezos-baker-012-Psithaca
--- a/tezos/mitten/tezos-baker-012-Psithaca
+++ b/tezos/mitten/tezos-baker-012-Psithaca
@@ -36,7 +36,7 @@ run_external_baker() {
                 if [ -n "$3" ]; then
                     CMD="$CMD --baker $3"
                     shift 3
-                elif [ -n $2 ]; then
+                elif [ -n "$2" ]; then
                     shift 2
                 else
                     shift
@@ -75,6 +75,11 @@ run_external_baker() {
 }
 
 run_internal_baker() {
+    if [ -z "$SENTRY" ]; then
+        export SENTRY=$$
+        "$0" "$@"
+        exit
+    fi
     while true; do
         case $1 in
             run|with|local)
@@ -120,14 +125,30 @@ run_internal_baker() {
         exit 1
     fi
 
-    BAKER=$(jq -r ".[] | select(.name == \"$BAKER\") | .value | sub(\".*:\"; \"\")" "$BASE_DIR/secret_keys")
-    echo "baker is $BAKER" >&2
-    while ! curl -q -X PATCH "$ENDPOINT/dev/shell/automaton/bakers" --data "$BAKER" >&2; do
+    SK=$(jq -r ".[] | select(.name == \"$BAKER\") | .value | sub(\".*:\"; \"\")" "$BASE_DIR/secret_keys")
+    baker_rpc() {
+        COMMAND=$1
+        curl -s -X PATCH "$ENDPOINT/dev/shell/automaton/bakers" --data "{ \"command\": \"$COMMAND\", \"baker\": \"$SK\" }"
+    }
+
+    echo "starting baker $BAKER" >&2
+    while [ "$(baker_rpc add)" != "true" ]; do
         echo Starting baker failed, retrying in 1 sec...
         sleep 1
     done
+    echo "baker $BAKER is started" >&2
 
-    sleep infinity
+    # mitten kills baker with KILL, no way to trap it, and it does not read its status, so it stays zombie
+    while [ -d "/proc/$SENTRY" ] && ! grep -q "zombie" "/proc/$SENTRY/status"; do
+        sleep 1
+    done
+
+    echo "stopping baker $BAKER" >&2
+    if [ "$(baker_rpc remove)" != "true" ]; then
+        echo "failed to stop baker $BAKER" >&2
+        exit 1
+    fi
+    echo "baker $BAKER is stopped" >&2
 }
 
 TEZEDGE_ENV=${TEZEDGE_ENV:-$(dirname "$0")/tezedge.env}
